
java:
  runtime:
    version: 11
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://jtest.cvborikedhwv.ap-northeast-2.rds.amazonaws.com:3306/body.gg?serverTimezone=UTC&characterEncoding=UTF-8
    username: admin
    password: 12345678
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: false
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      format_sql: true
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /console
  thymeleaf:
    cache: false
server:
  session:
    tracking-modes: cookie

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.body.gg.domain.mapper
